version: '3.9'
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
    - .env
    container_name: php_app
    volumes:
    - ./php:/var/www/html
    ports:
      - "8080:80"

  db:
    image: postgres:16
    container_name: pg_db
    environment:
      POSTGRES_DB: catalogo
      POSTGRES_USER: catalogo_user
      POSTGRES_PASSWORD: catalog_pass
      TZ: America/La_Paz
      PGTZ: America/La_Paz
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
