services:
  - type: web
    name: rendertest
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/IBertoo/remote_repo  # Reemplaza con tu repo
    region: Ohio  # Ajusta a tu región
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: catalogo
          property: connectionString  # Render lo inyecta automáticamente, pero esto lo asegura
